// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "7ff1feae-c074-45f9-ad4f-2e8c760774f8";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onValChange();
void onEnabledChange();

int val;
bool enabled;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(val, READWRITE, 1 * SECONDS, onValChange);
  ArduinoCloud.addProperty(enabled, READWRITE, 1 * SECONDS, onEnabledChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
