#include "arduino_secrets.h"
#include "thingProperties.h"

/* 
  Sketch generated by the Arduino IoT Cloud Thing "light_sensor"
  https://create.arduino.cc/cloud/things/6727e4e6-48b1-4215-84fa-b6492e106a60 
  Arduino IoT Cloud Variables description
  The following variables are automatically generated and updated when changes are made to the Thing
  bool light;
  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

int inputLight = 36;
int lightValue = 0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() 
{
  ArduinoCloud.update();
  
  //read the value from the light sensor
  lightValue = analogRead(inputLight);
  Serial.println(lightValue);

  //check the value read from the light sensor
  if (lightValue >= 4095)
  {
    light = true;
    Serial.println("LOW AMBIENT LIGHT --> TURNING SYSTEM ON...");
  }
  else 
  {
    light = false;
    Serial.println("HIGH AMBIENT LIGHT --> TURNING SYSTEM OFF...");
  }
  
  delay(10000);
  
}

/*
  Since Light is READ_WRITE variable, onLightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightChange()  {
  // Add your code here to act upon Light change
}
